#!/bin/bash
docker-compose down -v --rmi all --remove-orphans && \
DB_PASSWORD="letmein123" SECRET_KEY_BASE='secretkeybase' docker-compose build --parallel && \
DB_PASSWORD="letmein123" SECRET_KEY_BASE='secretkeybase' docker-compose up
